spring:
    application:
        name: ms-config-server
    cloud: 
        config:
            server:
                git:
                    uri: https://github.com/Mauro8500/server-config/tree/main
                    default-label: "main"
server:
    port: 8888